{% set name = "TNAgen" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/TNAgen-{{ version }}.tar.gz
  sha256: 3b283731cad75921d4b815521bc30247ca41848995c7647e2b7f9db51d6081d8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10.8
    - setuptools >=61.0
    - pip
  run:
    - python >=3.10.8

test:
  imports:
    - TNAgen
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sStaite/TNAgen
  summary: A package that generates transient noise artifacts in gravitational-wave detector data.
  license: GPL-3.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - sStaite
